{ pkgs, config, ... }:

{

home.file = {
  ".config/hypr/hyprland.conf".text = ''
########################################################################################
AUTOGENERATED HYPR CONFIG.
PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
########################################################################################

#
# Please note not all available settings / options are set here.
# For a full list, see the wiki
#

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = swww init
exec-once = hyprbg ~/Imagens/Wallpapers
exec-once = foot -T ft
exec-once = udiskie
exec-once = dunst
exec-once = syncthing -no-browser
exec-once = waybar

autogenerated = 0 # remove this line to remove the warning

# See https://wiki.hyprland.org/Configuring/Monitors/
#monitor=,highres,auto,auto
monitor=,1920x1080@59.98,0x0,1

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
# exec-once = waybar & hyprpaper & firefox

# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = pt
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    float_switch_override_focus = 0
    mouse_refocus=0
    numlock_by_default = true

    touchpad {
        natural_scroll = yes
        disable_while_typing = yes
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 5
    gaps_out = 5
    border_size = 1
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(59595900)
    cursor_inactive_timeout = 1

    layout = master
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 5
    blur {
      size = 3
      passes = 1
      new_optimizations = on
    }

    drop_shadow = no
}

animations {
  enabled = no

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 1, default
    animation = workspaces, 1, 1, default
    animation = specialWorkspace, 1, 1, default, slidevert
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
    force_split = 1
    permanent_direction_override = true
    no_gaps_when_only = true
    special_scale_factor = 1
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = true
    no_gaps_when_only = true
    new_on_top = true
    special_scale_factor = 1
    #always_center_master = true
    #orientation = center
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = true
    workspace_swipe_fingers = 3
    workspace_swipe_forever = true
}

misc {
  disable_hyprland_logo = true
  mouse_move_enables_dpms = true
  no_direct_scanout = true #for fullscreen games
}

binds {
  workspace_back_and_forth = false
  allow_workspace_cycles = true
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
device:epic mouse V1 {
    sensitivity = -0.5
}

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more


# See https://wiki.hyprland.org/Configuring/Keywords/ for more

$BROWSER = librewolf
$Mod = SUPER

windowrule = workspace 1,title:(Firefox)$
windowrule = workspace 1,title:(Chromium)$
windowrule = workspace 1,title:(Librewolf)$
windowrule = workspace 2,^(foot)$
windowrule = workspace 5,^(Logseq)$
windowrule = workspace 3,^(imv)$
windowrule = workspace 3,^(qimgv)$
windowrule = workspace 3,swayimg
windowrule = workspace 4,^(mpv)$
windowrule = workspace 4,^(Popcorn-Time)$
windowrule = workspace 6,title:(WhatsApp for Linux)$
windowrule = workspace 4,title:^(Picture in picture)$
windowrule = workspace 5, qutebrowser
windowrule = workspace 5, qemu
windowrule = workspace 5,title:(LibreOffice)$
windowrule = workspace 6,title:(Telegram)$
windowrule = workspace 6,title:Signal
windowrule = workspace special:floaterm silent,title:(ft)$
windowrule = workspace special:logseq,^(Logseq)$
windowrule = float,title:(ft)$
windowrule = dimaround,title:(ft)$
windowrule = noblur,title:(foot)$
windowrule = animation none,^(Chromium)$
windowrule = noblur,^(Chromium)$
windowrule = workspace special:keepassxc silent,title:(KeePassXC)$
windowrule = float, Rofi
windowrule = animation none,Rofi

bind = $Mod, Return, exec, foot
bind = $Mod, C, exec, swww clear
bind = $Mod, 2, exec, pidof -o $(pidof -s foot) foot || foot
bind = $Mod SHIFT, Return, exec, tofirun
#bind = $Mod, Q, killactive,
bind = $Mod, Q, exec, hyprspace
#bind = $Mod SHIFT, Q, exit,
bind = $Mod SHIFT, Q, exec, hyprquit
bind = $Mod, 1, exec, pidof $BROWSER || $BROWSER
bind = $Mod, T, exec, telegram-desktop
bind = $Mod, F, exec, firefox
bind = $Mod, W, exec, pgrep qutebrowser || ${pkgs.qutebrowser-qt6}/bin/qutebrowser
bind = $Mod, W, workspace, 5
bind = $Mod, A, exec, [workspace special:keepassxc silent] ${pkgs.keepassxc}/bin/keepassxc
bind = $Mod, T, workspace, 6
bind = $Mod, F, togglefloating,
bind = $Mod, P, pseudo, # dwindle
bind = $Mod, J, togglesplit, # dwindle
bind = $Mod, B, exec, hyprbar
bind = $Mod, V, exec, mpv "$(wl-paste)"
bind = $Mod SHIFT, R, exec, hyprctl reload,
bind = $Mod, Plus, exec, pactl set-sink-volume 0 +10%
bind = $Mod, Minus, exec, pactl set-sink-volume 0 -10%
bind = $Mod SHIFT, Plus, exec, light -A 5
bind = $Mod SHIFT, Minus, exec, light -U 5
bind = $Mod, M, exec, pactl set-sink-mute 0 toggle
bind = $Mod SHIFT, Backspace, exec, clreboot
bind = $Mod SHIFT, Delete, exec, clpoweroff
bind = $Mod, BackSpace, exec, ${pkgs.swaylock}/bin/swaylock -u -c "#000000"
bind = , F8, exec, blue
bind = $Mod, TAB, exec, hyprV

# Move focus with mainMod + arrow keys
bind = $Mod, left, movefocus, l
bind = $Mod, right, movefocus, r
bind = $Mod, up, movefocus, u
bind = $Mod, down, movefocus, d
bind = $Mod, Z, layoutmsg, swapwithmaster master
bind = $Mod, backslash, workspace, previous
bind = $Mod, I, layoutmsg, addmaster
bind = $Mod, D, layoutmsg, removemaster
bind = $Mod SHIFT, period, layoutmsg, orientationnext
bind = $Mod SHIFT, comma, layoutmsg, orientationprev

# Switch workspaces with mainMod + [0-9]
bind = $Mod, 1, workspace, 1
bind = $Mod, 2, workspace, 2
bind = $Mod, 3, workspace, 3
bind = $Mod, 4, workspace, 4
bind = $Mod, 5, workspace, 5
bind = $Mod, 6, workspace, 6

#bind = $Mod, A, togglespecialworkspace, keepassxc
bind = $Mod, Less, togglespecialworkspace, floaterm
bind = $Mod, A, exec, pidof logseq || logseq
bind = $Mod, A, togglespecialworkspace, logseq

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $Mod SHIFT, 1, movetoworkspace, 1
bind = $Mod SHIFT, 2, movetoworkspace, 2
bind = $Mod SHIFT, 3, movetoworkspace, 3
bind = $Mod SHIFT, 4, movetoworkspace, 4
bind = $Mod SHIFT, 5, movetoworkspace, 5
bind = $Mod SHIFT, 6, movetoworkspace, 6

# Scroll through existing workspaces with mainMod + scroll
bind = $Mod, Period, workspace, e+1
bind = $Mod, Comma, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $Mod SHIFT, Z , movewindow
bindm = $Mod, Alt_L, resizewindow

# resize submap (mode)
bind  = $Mod,R,submap,resize
submap  = resize
binde = ,right,resizeactive,40 0
binde =  ,left,resizeactive,-40 0
binde =  ,up,resizeactive,0 -40
binde = ,down,resizeactive,0 40
bind= , escape,submap,reset
bind= , Return,submap,reset
submap  = reset

bind = , Print, submap, shot
submap = shot
bind = , Print, exec, screenshot --now
bind = , A, exec, screenshot --area
bind = , W, exec, screenshot --win
bind = , 5, exec, screenshot --in5
bind= , escape,submap,reset
submap = reset
'';
};

}
